### ISSUE TITLE
Change return type of ViewTuple.getView() from Parent to Node

### ISSUE THREAD

**Issue by manuel-mauky** [sialcasa/mvvmFX#102]
At the moment the `ViewTuple.getView()` method returns a `Parent`. 
Internally there is a Cast from the loaded view to `Parent`.

This produces two problems that should be fixed with this issue: 
1. When the user tries to load a `JavaView` that isn't subclassed from a JavaFX element a pure `ClassCastException` is thrown. Instead we should provide an exception with a useful 
 message.
2. This way the user can't derive directly from `Node` or another JavaFX class that isn't a subclass of `Parent` like for example `ImageView`.

We should change the return type to `Node`. This wouldn't break the API because Node is a Parent.

**Comment by manuel-mauky** [comment]
I'm wrong: Parent _is a_ Node but Node _is not a_ Parent. 
This means that the API will break.
`Parent view = viewTuple.getView();` will not compile anymore.

Do we still want to change this? In my oppinion using _Parent_ as return type is still wrong and _Node_ would be the right choice for the return type.

**Comment by sialcasa** [comment]
mh let's have a call

**Comment by manuel-mauky** [comment]
We won't fix that issue because the constructor of 'Scene' are taking a parameter of type 'Parent'. 
If we would change the type of our view to 'Node' you wouldn't be able to use a mvvmfx-view as the root of a scene directly. This is a no-go as it makes using mvvmFX more difficult.
