### ISSUE TITLE
Change Events bei Benutzung der ListTransformation werden nicht weiter geleitet

### ISSUE THREAD

**Issue by spaxx86** [sialcasa/mvvmFX#114]
Ich habe in meinem Model eine ObservableList und möchte diese mit einer ObservableList in meinem ViewModel synchronisieren. Wird ein Element der Liste in meinem Model geändert, so wird diese Änderung nicht an meine Liste im ViewModel weiter geleitet.

```
private ObservableList<BookingViewModel> bookingViewModel;
private ObservableList<Booking> bookingsModel;



ListTransformation<Booking, BookingViewModel> transform = new ListTransformation<Booking, BookingViewModel>(bookingsModel, booking ->{
            BookingViewModel viewModel = new BookingViewModel();

            // meine Mapping Logik

            return viewModel;
        });

bookingViewModel = transform.targetListProperty();

```

Damit die Changes weiter geleitet werden muss folgender Aufruf gemacht werden.

```
bookingsModel.addListener((ListChangeListener.Change<? extends Booking> listChangeListener) -> transform.modelListProperty());
```

Scheinbar liegt das Problem an dem WeakListChangeListener. Dort wird vermutlich die Referenz weggeräumt wenn der vorherige Aufruf nicht gemacht wird.

**Comment by manuel-mauky** [comment]
Der WeakListChangeListener wird benutzt um Memory-Leaks zu verhindern. Deshalb sollten wir den nicht ausbauen. Stattdessen kannst du das Problem sauberer Lösen wenn du eine Referenz auf die ListTransformation Instanz behältst. 

Implizit passiert das auch durch deinen Listener: Da innerhalb des Lambdas auf die Umgebung zugegriffen wird, wird das Lambda zu einer anonymen inneren Classe kompiliert, die eine Referenz auf die ListTransformation-Instanz hält. Dies wiederum verhindert die Garbage-Collection der Listener.
