### ISSUE TITLE
Make it possible to register custom BuilderFactories

### ISSUE THREAD

**Issue by manuel-mauky** [sialcasa/mvvmFX#131]
In some use cases you need a custom [BuilderFactory](http://docs.oracle.com/javase/8/javafx/api/javafx/util/BuilderFactory.html) for your own components. 
We should provide a way to add such factories to our framework so that thay are set in the internal FXMLLoader. 

We could create our own BuilderFactory that first iterates over the provided custom BuilderFactories when a builder is [requested](http://docs.oracle.com/javase/8/javafx/api/javafx/util/BuilderFactory.html#getBuilder-java.lang.Class-) and after that (if no suitable builder was found) and then forward the request to the default [JavaFXBuilderFactory].

**Comment by sideisra** [comment]
I have a related problem. I need to give View and ViewModel some further information based on the loaded fxml file. Therefore i would need lifecycle methods that give me access to FXML, View and ViewModel when creating these instances. Like a Builder from a custom BuilderFactory but I need to know from what fxml the view has been created.

Example: I have a generic view and a generic view model which serve as code behind for different fxml files. But there is some fxml specific logic so I need to know the fxml file name in view and/or view model. With the name of the fxml file I load other files which are equally names (e.g. main.fxml > main.xml). 

Would it be possible to implement this addition here or should it be a separate feature request?

**Comment by manuel-mauky** [comment]
This should be a separate feature request. Could you please open a new ticket for this? Can you provide some more details of your example? Especially how do you use your "generic view"/"generic viewmodel"? Are you using sub-classing or do you bypass the naming conventions when you load the view?

**Comment by sialcasa** [comment]
@dennyisrael @lestard https://github.com/sialcasa/mvvmFX/issues/215 is related to this topic
