### ISSUE TITLE
FXMLLoader should autodetect the root class if it is not defined by setting setRoot

### ISSUE THREAD

**Issue by sialcasa** [sialcasa/mvvmFX#143]
RootElementView (extends AnchorPane)
RootElementView.fxml (with a defined anchorpane root)

FluentViewLoader.fxmlView(RootElementView.class).load();  //this should not throw an exception because the root can be autodetected with the naming convention and a check, whether the View extends the type which is defined in the FXML

**Comment by manuel-mauky** [comment]
Is there an (easy) way to find out the root element of a FXML file before it is loaded?

**Comment by sialcasa** [comment]
Archived
