### ISSUE TITLE
CDI: make mvvmfx-cdi independend from Weld

### ISSUE THREAD

**Issue by manuel-mauky** [sialcasa/mvvmFX#149]
We should find out if we can make the mvvmfx-cdi module independend from Weld-SE because Weld isn't the only CDI implementation out there. 
The goal would be that the mvvmfx-cdi module only depends on the cdi api and the user has to add an implementation dependency for her project. This way we could support other implementations like OpenWebBeans too.

**Comment by manuel-mauky** [comment]
Maybe Apache DeltaSpike can help to implement this. See this for example:
https://github.com/os890/javase-cdi-ds-project-template

**Comment by mainrs** [comment]
what about https://bitbucket.org/gluon-oss/ignite/src ?
It is a layer between different DI frameworks. Exchanging the jar would be enough to use dagger instead of guice. This could be used to create a new implementation for Weld.

**Comment by rguillens** [comment]
CDI 2.0 and it's RI, Weld 3.0 were released this week. If I understood well, CDI 2.0 provides a proper way of bootstrapping SE containers without referencing the underlying implementation.

**Comment by manuel-mauky** [comment]
Yes, this is correct. CDI 2 seems to be a good solution for this problem. I haven't had the time to take a closer look at it but it's promising. 
However, this update has to be backwards compatible. Existing projects that are using the current version still have to work. A possible solution could be to rename the existing `mvvmfx-cdi` module to `mvvmfx-weld` or `mvvmfx-cdi-legacy` or something like this and to create a new `mvvmfx-cdi` module based on CDI 2. Or keep the old module and create a new `mvvmfx-cdi2` module.

**Comment by rguillens** [comment]
As current `mvvmfx-cdi` module is based on Weld renaming it to `mvvmfx-weld` is an option, I prefer a new module named `mvvmfx-cdi2` because existing projects doesn't need to change anything.

I've tested CDI 2.0 with the current `mvvmfx-cdi` and looks like a simple change; check my [PR](https://github.com/sialcasa/mvvmFX/pull/488)

**Comment by manuel-mauky** [comment]
Both the contacts-example and the mini-examples/welcome-example projects are still using the old CDI implementation and now don't work anymore. We have forgotten to update them before merging the PR. 
Therefore we still need to update both examples.

**Comment by rguillens** [comment]
Yes, we forgot, these projects now need to declare the Weld 3 dependency directly.
