### ISSUE TITLE
Scopes

### ISSUE THREAD

**Issue by manuel-mauky** [sialcasa/mvvmFX#154]
There should be the possibility to define scopes to group views together. 
This could be implemented in a way that there is a "Scope-ViewModel" that is injected into the viewModels.

**Comment by sialcasa** [comment]
References to ViewModels in a scope should be weak.

**Comment by manuel-mauky** [comment]
In the current proposal the scope has no references to the viewmodels at all. Instead the viewModels get the scope injected and have a reference to the scope.
Pro:
- You can add new View/ViewModels to the Scope without changing the Scope object. It's more pluggable. Every ViewModel that is interested in the Scope's data can request a Scope instance for injection

Cons:
- The ViewModel is more coupled to the Scope. This way it's not possible to create independend ViewModels that can be used everywhere. Instead they have a reference to a scope that comes from the environment of the ViewModel.

**Comment by manuel-mauky** [comment]
It is possible to have multiple Scopes of different types injected to a ViewModel. Multiple Scopes of a single type aren't usable because when the scope is created we can't easily decide which of the two scopes in the ViewModel is meant.

```
public class MyViewModel implements ViewModel {
    @InjectScope
    private MyScope scopeA;
    @InjectScope
    private MyScope scopeB;
}

....
MyScope scope = new MyScope();
ScopeHelper.initScope(scope, viewModel); 
```

In the above example, which scope instance should be injected? "scopeA" or "scopeB"?

**Comment by sialcasa** [comment]
@mthiele has new input :-)

**Comment by sialcasa** [comment]
Scope UseCases:
- Notifications between ViewModels
- DataContext between ViewModels

**Comment by sialcasa** [comment]
Please check branch Scopes_154

**Comment by manuel-mauky** [comment]
We have implemented a first beta version of a scopes mechanism. Let's try out how it works and if it solves our problems. Until then we will keep this issue open.
