### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by sialcasa** [sialcasa/mvvmFX#193]
A command combines an action with a condition. This can be used for example to provide an {@link #execute()}-action which should perform on a button click. The button should be disabled, while the Command is not executable.

**Comment by sialcasa** [comment]
Implemented 2 Variants of Commands
- DelegateCommand
- CompositeCommand

The DelegateCommand is able to run async. The CompositeCommand can compose Commands (sync and async).

**Comment by sialcasa** [comment]
Usage in ViewModel:

``` java
//ViewModel creates Command and offers it to the View - last parameter signals async processing in background thread
loginCommand = new DelegateCommand(() -> performLogin(), createLoginPossibleBinding(), true);
```

Usage in View:

``` java
//View Uses the command to delegate an Event
      @FXML
    void loginButtonPressed(final ActionEvent event) {
        loginCommand.execute();
    }

....
//View uses Command to activate / deactivate interactions if the command is not ready (Ready = Command is executable + Command is not Running)
//View uses Command to indicate the processing of the command
loginButton.disableProperty().bind(loginCommand.executeableProperty().not());
loginProgressIndicator.visibleProperty().bind(loginCommand.runningProperty());
```

**Comment by sialcasa** [comment]
Command has two state parameters

isExecutable - The user-provided condition is true and the command could execute + Command is not Running
isRunning - The command was executed and is running - important for long-running tasks

**Comment by manuel-mauky** [comment]
A question about this code fragment:

``` java
@FXML
void loginButtonPressed(final ActionEvent event) {
    loginCommand.execute();
}
```

Are there use cases where the `ActionEvent` is needed in the command? Do we need an overloaded `execute` method that gets the event as parameter? like this:

``` java
@FXML
void loginButtonPressed(final ActionEvent event) {
    loginCommand.execute(event);
}
```

On the other side the `ActionEvent` is view specific and maybe shouldn't be passed into the command?

**Comment by sialcasa** [comment]
Good question whether there is a use case. 

I think the main question is, can we pass any kind of parameter with the execute. If there would be the possibility to pass parameters, you would have the choice to pass necessary data from the ActionEvent to the ViewModel. Not sure about that...

**Comment by sialcasa** [comment]
Have a look here: https://msdn.microsoft.com/en-us/library/microsoft.practices.prism.commands(v=pandp.50).aspx

There is a generic implementation for a parameterized command. Do you have an idea to provide an optional parameter with the current implementation?

**Comment by sialcasa** [comment]
A Bad thing with parameterized commands is that they are hard to compose, because the un-unified  interface

**Comment by manuel-mauky** [comment]
For the first version we will stay with parameter-less commands. This will be suitable for a majority of use cases. For other use cases where parameters would be useful (f.e. mouse coordinates) we will think of a solution in the future (issue #198).
