### ISSUE TITLE
Load css files via naming conventions

### ISSUE THREAD

**Issue by manuel-mauky** [sialcasa/mvvmFX#213]
If there is a css file with the same name as the fxml file we could load this file automatically. 
`Example.css`
`Example.fxml`

**Comment by sialcasa** [comment]
I think this feature is not necessary, because the user hast to configure the css file in the fxml file, otherwise he won't get a preview in the scenebuilder

**Comment by manuel-mauky** [comment]
Ok that's a good point. As it's easy to define the css file in the fxml without much boilerplate, the benefit would be small anyway.
