### ISSUE TITLE
Using of lists in background model

### ISSUE THREAD

**Issue by KleinerHacker** [sialcasa/mvvmFX#214]
Hello,
I have a problem to use lists in background model via MVVM. I explain it with an example:

I have a book with a list of chapters. The chapter contains a title, a description and an image. On UI I have a list on left site to select a chapter, on the right site there is a pane to change chapter settings. 
In MVVM style I create a ChapterSettingsPane (FX-Pane), a ChapterSettingsView (Code Behind) and a ChapterSettingsViewModel. In the view model I set a chapter via the ModelWrapper and create the properties like 'titleProperty'. Then I bind bidirectional it to the text box in the UI (Code Behind).
The second step is the list item: I create a ChapterItemPane (FX-Pane), a ChapterItemView (Code Behind) and a ChapterItemViewModel with a model wrapper for the Chapter-Object. Here I create a 'titleProperty', too, and bind it on a label in the item view (Code Behind). The problem is, if I change the title via the Settings Pane there are no effect on the list item, cause the model wrapper creates different property instances for 'titleProperty'. I read the article 'how to use list views', but the solution is not nice, cause the list must contains the ChapterSettingsViewModel and, the second problem is, that the change of the list (add / remove) is not to handle via view model of book settings view: If I use the model wrapper with a book and create a property of type 'Property<ObservableList<ChapterSettingsViewModel>>' it is not be able to add an list change listener cause the getter in the field method is called more than one times, I believe.
In the article this handling is not explained. 

What is the best way to handle this problem?

**Comment by manuel-mauky** [comment]
Hi,
1) The `field` method of the ModelWrapper is overloaded. You need the [one that takes a String as the first argument](https://sialcasa.github.io/mvvmFX/javadoc/1.1.0/mvvmfx/de/saxsys/mvvmfx/utils/mapping/ModelWrapper.html#field-java.lang.String-java.util.function.Function-java.util.function.BiConsumer-). This string is an identifier that we use internally to return the same property instance when the method is called a second time. We know that this isn't a very clever way of handling this. Maybe we find a better approach in the future ;-) 
In the [wiki](https://github.com/sialcasa/mvvmFX/wiki/ModelWrapper) example we used the field name as string identifier. 
I hope the answer fixes your problem. If not, please don't hesitate to ask again :-)

2) I don't know if I'm understand the other problem with the ListView correctly. The approach with the ObservableList of ViewModels that is used as "items" of the ListView is a recommendation from us but surely there are other ways of handling this too. 
At the moment I don't know where the problem of your code is but if you could provide some example code I will take a closer look at it.

**Comment by KleinerHacker** [comment]
Hi, thanks for your answer.
To 1: This cannot help me cause I have more than one instance of ModelWrapper with the same instance in it. The property-fields are collected in a local class field (list) so that the both ModelWrapper instances do not share the property-field-instance.
To 2: Here is an example:

<pre>
public Property<ObservableList<ChapterViewModel>> chapterListProperty() {
  return modelWrapper.field(
    book -> new ObservableListWrapper<>(book.getChapterList().stream().map(...).collect(...)),
    book, chapterList -> {/* Never called cause instance not changed, but content like add / remove */} 
  );
}
</pre>

In this code you see that the field only map the chapter list into the view model. Than all UI instances work on the observable list and do changes on it. No changes will be delegate to the original background model list cause the instance will never be changed and the setter is never called. The sole solution is to add a ListChangeListener, but I do not know that is the correct way to do this in the getter lambda... When the lambda is called?

**Comment by manuel-mauky** [comment]
To 1: If I understand you correctly this is the same topic that you have requested in #219? 

To 2: You are right: At the moment we have no good support for collections in the ModelWrapper. I have created the issue #221 for this feature. 
For the first version of the ModelWrapper we had only simple form applications in mind but apparently there are many more use cases that we need to address now. :-)

The getter lambda is invoked when the field is added and every time the `reload` method is invoked on the wrapper. I can't think of a suitable way of implementing your use case with the given version of the ModelWrapper. I think there are changed needed in the ModelWrapper itself (#221).

**Comment by manuel-mauky** [comment]
As the problems mentioned in here are addressed in their own issues (#219 and #221) I will close this issue now. If you still think there are questions open related to this isseu feel free to open it again.
