### ISSUE TITLE
consolidate examples

### ISSUE THREAD

**Issue by manuel-mauky** [sialcasa/mvvmFX#217]
At the moment we have a lot of examples with different scope. We should consolidate them.
- [x] remove `mvvmfx-complex-example`, `mvvmfx-cdi-starter` and `mvvmfx-guice-starter` because the structure of this examples isn't very clear
- [x] add a sub-module `small-examples` to `examples`. Move the small examples into this sub module (`mvvmfx-fx-root-example`, `mvvmfx-helloworld-without-fxml`, `mvvmfx-helloworld` and `mvvmfx-synchronizefx`)
- [x] ~~add a small example that show how to use mvvmfx-cdi and mvvmfx-guice~~
- [x] ~~remove the sufix "-example" for the modules~~

After this we will have only three "big" application examples: 
- `mvvmfx-books`
- `mvvmfx-contacts`
- `mvvmfx-todomvc`

**Comment by lestard** [comment]
this should be done during the switch to gradle #150

**Comment by manuel-mauky** [comment]
- [x] update documentation
  - [x] wiki pages
  - [x] readme files
- [x] create missing readme files
