### ISSUE TITLE
Make progress of async command visible

### ISSUE THREAD

**Issue by manuel-mauky** [sialcasa/mvvmFX#218]
At the moment the commands have a `runningProperty`. When using Async commands we can use this to show a loading indicator. 
But in some use cases I would like to show the progress of the command with a progress bar. In this case a boolean isn't sufficient. Instead I need a percentage value (double).

**Comment by sialcasa** [comment]
- first thought: sounds like the Task interface with executable extension ^^
- second thought: its not like the Task interface, because the valueProperty is not MVVM conform (Value list is in the ViewModel and should not be in the Task)

**Comment by manuel-mauky** [comment]
This will be possible with feature #225.
Therefore I'm closing this issue now.
