### ISSUE TITLE
Multiple ModelWrapper instances with same model instance

### ISSUE THREAD

**Issue by KleinerHacker** [sialcasa/mvvmFX#219]
Hello,
the ModelWrapper contains a problem with using of more than one instance:

<pre>
final TestClass testClass = new TestClass("Name");
        final ModelWrapper<TestClass> modelWrapper1 = new ModelWrapper<>(testClass);
        final ModelWrapper<TestClass> modelWrapper2 = new ModelWrapper<>(testClass);

        final Property<String> nameProperty1 = modelWrapper1.field("name", TestClass::getName, TestClass::setName, "");
        final Property<String> nameProperty2 = modelWrapper2.field("name", TestClass::getName, TestClass::setName, "");

        final AtomicInteger counter1 = new AtomicInteger(0), counter2 = new AtomicInteger(0);
        nameProperty1.addListener((v, o, n) -> counter1.incrementAndGet());
        nameProperty2.addListener((v, o, n) -> counter2.incrementAndGet());

        Assert.assertEquals(counter1.get(), 0);
        Assert.assertEquals(counter2.get(), 0);

        nameProperty1.setValue("Hello");
        modelWrapper1.commit();

        Assert.assertEquals(counter1.get(), 1);
        Assert.assertEquals(counter2.get(), 0);
        Assert.assertEquals("Hello", testClass.getName());
        Assert.assertEquals("Hello", nameProperty1.getValue());
        Assert.assertEquals("Name", nameProperty2.getValue());

        modelWrapper2.reload();

        Assert.assertEquals(counter1.get(), 1);
        Assert.assertEquals(counter2.get(), 1);
        Assert.assertEquals("Hello", testClass.getName());
        Assert.assertEquals("Hello", nameProperty1.getValue());
        Assert.assertEquals("Hello", nameProperty2.getValue());
</pre>

What can I do when the instances of model wrappers are distributed in more than one class with no direct communication?

**Comment by manuel-mauky** [comment]
Hi, 

the ModelWrapper doesn't support auto-reloading. A ModelWrapper instance can't detect when there is a change directly in the model instance done through the setter of the model.  You have to use the `reload` method to get changes from the model instance to be reflected in the ModelWrapper. 

For your use case with two ModelWrapper instances distributed over more than one class I would suggest to use the NotificationCenter. When the `commit` is called in one place you could publish a notification. In all other places you can subscribe to this notification and invoke the `reload` method. 

``` java
public class MyViewModel1 implements ViewModel {
    private ModelWrapper<TestClass> wrapper = new ModelWrapper<>();
    ...
    public void okAction() {
         wrapper.commit();
         NotificationCenter.getInstance().publish("test_class_updated");
    }
}

public class MyOtherViewModel implements ViewModel {
    private ModelWrapper<TestClass> wrapper = new ModelWrapper<>();
    ...
    public MyOtherViewModel () {
        NotificationCenter.getInstance().subscribe("test_class_updated", (message, args) -> wrapper.reload());
    }
}
```
