### ISSUE TITLE
Support (observable) collections in ModelWrapper

### ISSUE THREAD

**Issue by manuel-mauky** [sialcasa/mvvmFX#221]
Support mapping of collection fields with the ModelWrapper:

``` java
public class Person {
    private List<String> nicknames = new ArrayList<>();
    public List<String> getNicknames() {
        return nicknames;
    }
    public void setNicknames(List<String> nicknames) {
        this.nicknames = nicknames;
    }
}

Person person = new Person();
private ModelWrapper<Person> wrapper = new ModelWrapper<>(person);

ListProperty<String> nicknames = wrapper.field(Person::getNicknames, Person::setNicknames);

nicknames.add("player");
wrapper.commit();

assertThat(person.getNicknames()).contains("player");
```

Additionally we should take care for use cases where the list in the model contains elements of another model class. In this case we need a some kind of conversion to be able to keep the model classes hidden from the View.

**Comment by lihop** [comment]
Hi there, I am currently using mvvmfx for a project and this feature would be really useful.
Has there been any progress made towards this?
Do you have any advice of how I could start implementing this?

**Comment by manuel-mauky** [comment]
Hi Leroy,
no we haven't had the time to work on this yet.

If there is only a list of a primitive type or String like in the example above, I think the code wouldn't be too complicated. We simply need to add a listener to the created ListProperty and keep track of the added/removed items. We can't directly transfer items in the moment they are added to the ListProperty because it's expected that the transfer only happens when `commit` is called. Therefore we need to "cache" the items some way but this should be possible.

This approach could even be used for lists of other types then primitives or Strings. 

But from the MVVM perspective this wouldn't be optimal because we don't want to have model objects in the View. So it should be possibile to define a mapping. On the other hand this problem doesn't only apply to lists but to normal fields too, which isn't working at the moment either. In the first step we could only implement the "normal" list wrapping without mapping functions. 

If you like to implement the list wrapping we would be happy. If you need further help just let us know.

For an idea of how a mapping could work see the following example:

``` java
public class Room {
...
}

public class Building {
    List<Room> rooms = new ArrayList<>();
    public List<Room> getRooms() {
        return rooms;
    }
    public void setRooms(List<Room> rooms) {
        this.rooms = rooms;
    }
}


public BuildingViewModel implements ViewModel {

    private Building building = new Building();
    ModelWrapper<Building> wrapper = new ModelWrapper<>(building);

    public ListProperty<Room> roomsProperty() {
        return wrapper.field(Building::getRooms, Building::setRooms);
    }
}
```

In this case the `BuildingViewModel` provides a ListProperty of type `Room` to the View but `Room` is a model class. Instead we would like to have something like this:

``` java
public RoomViewModel implements ViewModel {
    private ModelWrapper<Room> wrapper = new ModelWrapper();

    public RoomViewModel(Room room) {
        wrapper.set(room);
    }
    public Room getModel() {
        wrapper.get();
    }
}

public ListProperty<RoomViewModel> roomsProperty() {
     return wrapper.field(Buildings::getRooms, Buildings::setRooms, RoomViewModel::new, RoomViewModel::getModel); 
}
```

Maybe the field method could be overloaded to accept two additional converter functions that are used. The signature could be someting like this:

``` java
public <T, M, X> ListProperty<X> field(Function<M, List<T>> getter, BiConsumer<M,List<T>> setter, Function<T,X> targetTypeCreator, Function<X, T> listTypeCreator) 
```

`M` is `Building`
`T` is `Room`
`X` is `RoomViewModel`

The getter and setter are working like the existing ones in `ModelWrapper`. They are used to get and set the `List<Room>` on the `Building` class. 
The third function takes a `Room` and creates a `RoomViewModel` which is added to the target ListProperty. The fourth function takes a `RoomViewModel` and returns the `Room` instances that was wrapped by the `RoomViewModel`. This `Room` instance is then commited to the Room list in the Building. 

This looks quite complicated to implement but should be possible. I'm only worring that the poor type system of Java will get in our way :-(

**Comment by lihop** [comment]
Oops! Thanks for the reply, and I am very sorry for the spam above. 

I should add this is a group project for University. The commits above are our first attempt at adding list support. It works well for our needs.

**Comment by manuel-mauky** [comment]
Hi Leroy, 
thanks for your effort. I hope I can find the time to review your work within the next days. 
At the moment I'm relatively busy and don't have much time to work on mvvmFX.

**Comment by manuel-mauky** [comment]
This issue is now fixed with a basic implementation for simple element types.
A conversion of element types is not implemented yet. I've added the issue #299 for this.
