### ISSUE TITLE
dirty flag for model wrapper

### ISSUE THREAD

**Issue by sideisra** [sialcasa/mvvmFX#232]
With the ModelWrapper it is possible to access model data directly, collect changes and write them to the model (e.g. when the user hits "save"). It would be great when this ModelWrapper could tell me when the data have been changed by the user and a save action is necessary. This "dirty flag" should be available as property so I can bind a button state or another indicator to it.

**Comment by manuel-mauky** [comment]
Sounds like a good idea.
