### ISSUE TITLE
integrate jfx-testrunner in mvvmfx-testing-utils

### ISSUE THREAD

**Issue by manuel-mauky** [sialcasa/mvvmFX#247]
Include the [jfx-testrunner](https://github.com/sialcasa/jfx-testrunner) in mvvmfx-testing-utils.

**Comment by sideisra** [comment]
+1

**Comment by manuel-mauky** [comment]
I've added a modified version of the JfxRunner. Our version now uses the JFXPanel internally instead of starting a "real" application. The reason for this decision is that there were problems in combination with TestFX with the original JfxRunner. If you had JfxRunner tests and TestFX tests in the same build there was an `java.lang.IllegalStateException: Application launch must not be called more than once` thrown.

With the JFXPanel based JfxRunner this seems to work but I don't know if there are other issues with JFXPanel solution.
