### ISSUE TITLE
Allow the user to use custom path to fxml files

### ISSUE THREAD

**Issue by manuel-mauky** [sialcasa/mvvmFX#249]
Using convention over configuration the fxml file has to be in the same package as the CodeBehind class. If this isn't working for a user we should provide a way to configure a custom path to the fxml file. 

See this example:

``` java
package de.mycompany.myapp.MyView

@FxmlPath("/de/otherpath/OtherFilename.fxml")
public class MyView implements FxmlView<MyViewModel> {
}
```

**Comment by manuel-mauky** [comment]
reference #262

**Comment by rguillens** [comment]
I've implemented an initial approach to support this feature, check my [PR](https://github.com/sialcasa/mvvmFX/pull/489).

**Comment by manuel-mauky** [comment]
This feature is implemented but still needs documentation in the wiki. For this reason I'm keeping this issue open for now.
