### ISSUE TITLE
Injectable ViewModel in View

### ISSUE THREAD

**Issue by manuel-mauky** [sialcasa/mvvmFX#26]
At the moment in the View class you have to use `getViewModel()` to get the view model. 
It would be better to be able to inject the ViewModel with `@Inject`.

```
public class PersonLoginView extends View<PersonLoginViewModel>{
    @Inject
    private ViewModel viewModel;
    ...
}
```

This way the testablility is improved because you can inject a mock ViewModel in your test View. 

The DI-Framework has to find out the generic type of View to inject the correct instance. I don't know wether this is possible in CDI but we could try to find it out.

**Comment by sialcasa** [comment]
Yes - I'd like to have both possabilities. Getter access and Injection
