### ISSUE TITLE
ViewModel#publish not usable in Unittest

### ISSUE THREAD

**Issue by sideisra** [sialcasa/mvvmFX#263]
With the new 1.3.0 version I ran into the problem, that my unit tests break with the message:
`Toolkit not initialized`. This is because I use the `publish` and `subscribe` methods in my view models and I test the correct use of them in my unit test.

Unfortunately in version 1.3.0 the publish method now makes wraps the command in `Platform#runLater` and my unit tests are broken.

Could you please change that back so that I can test the notification behaviour in my unit tests? I will handle thread problems my self ;-).

**Comment by manuel-mauky** [comment]
I've added a utility that can simplify the testing of Notifications. This util takes care for the handling of the JavaFX application thread. I hope this can help you. See the wiki: https://github.com/sialcasa/mvvmFX/wiki/NotificationCenter#testing-notifications

**Comment by manuel-mauky** [comment]
If JavaFX wasn't bootstrapped, we are now directly publishing messages and not "Toolkit not initialized"-Exception will be thrown.
