### ISSUE TITLE
Allow customization of ViewListCells

### ISSUE THREAD

**Issue by mthiele** [sialcasa/mvvmFX#275]
When using `ListView`s with mvvmFX, the `CachedViewModelCellFactory` can be used to supply a View with its according View Model as items to the ListView. Those items are of type `ViewListCell` which is a specialization of `ListCell`.
Now I want to adjust the behaviour of the `ViewListCell` by calling:

``` java
listView.setCellFactory(new CachedViewModelCellFactory<>(viewModel ->
        FluentViewLoader.fxmlView(MyView.class).viewModel(viewModel).load()) {
      @Override
      public ViewListCell call(final ListView element) {
        final ViewListCell result = super.call(element);
        ...
        return result;
      }
    });
```

Unfortunately, I cannot do that since `ViewListCell` is of visibility package local. It would be really helpful if it were of visibility public to alter its behaviour.

**Comment by manuel-mauky** [comment]
Hi micha, 
good idea. It's done and you can test it with the current snapshot.
