### ISSUE TITLE
ListTransformation fires multiple add events on the target list when multiple elements are added to the source list

### ISSUE THREAD

**Issue by mthiele** [sialcasa/mvvmFX#281]
The `ListTransformation` implementation fires multiple ListChangeEvents on the target list when adding multiple elements to the source list (which is done in one event). This is a rather unexpected behaviour since the original add event is also one event and leads to problems with `FilteredList`s in conjunction with `ListTransformation` when the predicate of the `FilteredList` is reset.

My proposed change would be:

``` java
  private void processAddEvent(
      final Change<? extends SourceType> listEvent) {
    final List<TargetType> toAdd = new ArrayList<>();
    for (int index = listEvent.getFrom(); index < listEvent.getTo(); index++) {
      final SourceType item = listEvent.getList().get(index);
      toAdd.add(function.apply(item));
    }
    viewModelList.addAll(listEvent.getFrom(), toAdd);
  }
```

**Comment by manuel-mauky** [comment]
thanks for your suggestion. It's now fixed with #283
