### ISSUE TITLE
Support for fx:include and views

### ISSUE THREAD

**Issue by javlaks** [sialcasa/mvvmFX#297]
A lot of times we need to add fx:include to our FXMLs but we cannot access to its Controller until we add the @FMXL to call natively to the component.

If you could add an @InjectViewModel to the fx:include components or something similar, would be awesome, to connect one view model to another view model.

I think there is a way to implement this feature from your library to use easily.

**Comment by manuel-mauky** [comment]
Hi Víctor,
I'm not sure if I understand you correctly. 

See the following example: 
ChildView.fxml:

``` xml
<VBox fx:controller="example.ChildView">
   <children>
      <Label text="child" />
   </children>
</VBox>
```

ParentView.fxml:

``` xml
<VBox fx:controller="example.ParentView">
    <children>
        <Label text="parent"/>
        <fx:include source="ChildView.fxml" fx:id="child"/>
    </children>
</VBox>
```

Notice that the fx:include-tag has a `fx:id` attibute. With this setup I can now inject the view class of the child into the parent view class like this:

``` java
public class ParentView implements FxmlView<ParentViewModel> {
    @FXML
    public ChildView childController;

    @InjectViewModel
    private ParentViewModel viewModel;

    public void initialize() {
        System.out.println("child view:" + childController);
    }
}
```

The field has to be named "childController". First the `fx:id` value followed by "Controller". This mechanism is provided by standard JavaFX.

Is this what you asked for? 

Or do you what to inject the `ParentViewModel` into the `ChildView` or even `ChildViewModel`? 
This isn't possible at the moment. We have similar feature requests (#190, #215) but as we are using the standard FXMLLoader from JavaFX internally we are limited when it comes to the loading process of FXML files. 

You would need to pass the right viewModel instances into the ChildView by hand.

**Comment by javlaks** [comment]
Yeah, that is what I do actually, call natively like you.

My ideas is connect using the inject pattern to follow the same pattern in all views. However this method works fine.

It was just an idea. Thanks for review it!

**Comment by manuel-mauky** [comment]
Ok, in this case I will close this issue now and mark it as duplicate to #215 which asks for a similar feature. 
Anyway, thanks for your input.
