### ISSUE TITLE
Synchronous DelegateCommand does not executecallbacks

### ISSUE THREAD

**Issue by sideisra** [sialcasa/mvvmFX#310]
When using DelegateCommand in synchronous mode the callback methods "succeeded" and "failed" are not called after execution of the "action" method. When using DelegateCommand in ansynchronous mode these methods are called like using plain Task and Service.

It is confusing that these methods are not called just because the DelegateCommand is switched to synchronous mode.

```
new DelegateCommand(<action supplier definition>, true); // callbacks will be executed
new DelegateCommand(<action supplier definition>, false); // callbacks won't be executed
```

**Comment by manuel-mauky** [comment]
Reopend because the implementation forces the execution of the command on the UI thread which is a breaking change and bad for unit testing.
