### ISSUE TITLE
synchronous DelegateCommand suppresses exception

### ISSUE THREAD

**Issue by sideisra** [sialcasa/mvvmFX#311]
When using DelegateCommand in synchronous mode (`new DelegateCommand(<action supplier definition>);`) it runs the action synchronous. I saw in the cod that the call to `action` is surrounded by try-catch and the caught exception is just printed in the console (`e.printStackTrace()`) so i have no chance to react on execution problems. It would be better to rethrow the exception as RuntimeException to give the caller a chance to react on it.

**Comment by sialcasa** [comment]
ouch - we'll fix
