### ISSUE TITLE
ViewModel isn't initialized under some specific conditions

### ISSUE THREAD

**Issue by manuel-mauky** [sialcasa/mvvmFX#314]

**Comment by sialcasa** [comment]
@lestard  could the reason be https://github.com/sialcasa/mvvmFX/issues/332

**Comment by manuel-mauky** [comment]
Added test cases to reproduce the bug. To solve the bug I will further investigate next week. I will also look at #332.

**Comment by manuel-mauky** [comment]
We will fix this issue with the next version of mvvmFX and **not** with the bugfix release.
The reason is that this issue implies some deeper changes of the initialization logic. It turns out that there are some special cases where the answers to questions like "should we inject this and that?" or "should we initialize the ViewModel/View?" aren't that clear and need further discussion and testing. For example: Loading a View with an existing CodeBehind and this CodeBehind already has a ViewModel instance. Should we initialize the existing ViewModel? Maybe the ViewModel is already initialized and reinitializing it can cause exceptions?
