### ISSUE TITLE
Inconsistence between Java and FXML views when no VM type is specified

### ISSUE THREAD

**Issue by manuel-mauky** [sialcasa/mvvmFX#319]
With the `@InjectViewModel` annotation you can only inject a ViewModel into the View when the type of the to-be-injected ViewModel matches the generic type of the View. Something like this isn't possible:

``` java
public class MyView implements FxmlView<TestViewModelA> {
    @InjectViewModel
    private TestViewModelB viewModel; // wrong type
}
```

However, when the View has no generic type defined for the ViewModel the behaviour is different for FxmlViews and JavaViews at the moment. 
In the case of FxmlView the same exception is thrown that is thrown on wrong ViewModel type.
In the case of JavaView no exception is thrown. 

To fix this we need to change the behaviour of JavaView loading process and throw an exception in this case.

**Comment by sialcasa** [comment]
@lestard can this issue be closed?

**Comment by manuel-mauky** [comment]
@sialcasa done
