### ISSUE TITLE
Problem with initialize method and CDI/Guice singletons

### ISSUE THREAD

**Issue by manuel-mauky** [sialcasa/mvvmFX#343]
When a DI framework is used the following is happening when a ViewModel is requested:
1. request an instance for the given ViewModel type from the DI framework
2. DI framework creates an instance, injects dependencies and calls `@PostConstruct` method
3. we inject all mvvmfx specific stuff
4. call `initialize` method if available

This sequence is the reason why we can't use mvvmfx resources in the `@PostConstruct` method at the moment. For example you can't use injected resourceBundles. 
But there is another problem with this approach:
Given a ViewModel class is annotated with `@Singleton`. If there is a view loaded a second time where this viewModel is used the above process is taking place a second time. The DI framework will return the existing ViewModel instance but the mvvmfx framework part  can't know about the fact that the ViewModel is a singleton. So the steps 3 and 4 will take place a second time. This can produce big problems for example if the initialize method is used to create unidirectional bindings ("a bound value cannot be set" exception).

**Comment by sialcasa** [comment]
For problem 2:

What about an atomicboolean initialized as a final static member in the viewmodel interface, that indicates whether the vm was already initialized. Then we could skip to call initialize in the second case.

**Comment by manuel-mauky** [comment]
This would not be a general solution. We would need to detect whether the instance is a singleton or not. We would need to detect whether the `@Singleton` annotation is present or not. But this depends on the DI framework. For example with [EasyDI](https://github.com/lestard/EasyDI) you can define a singleton without the `@Singleton` annotation. 
In the AIDA project we are using a custom annotation for singletons so this wouldn't work too.

In my opinion we should do the following:
1. change the semantics of the `initialize` method from "is called after the view is created" to "is always called after the view is loaded". If the view is loaded multiple times of cause this method would be called multiple times too. This is the current behaviour and maybe this is ok. We only need to describe it better so that the behaviour is clear. If you think about the standard `initialize` method of JavaFX controller classes it's the same behaviour. Maybe this issue isn't even a problem but perfectly fine. We only need to update the docs.
2. Provide a better integration for our CDI and Guice modules so that `@PostConstruct` methods are called after the mvvmfx stuff is injected. This would still be called only a single time when Singletons are used. At the moment I have no idea if this is possible or how hard it may be. 

What do you think?
