### ISSUE TITLE
Update releases at mvnrepository.com

### ISSUE THREAD

**Issue by bennetelli** [sialcasa/mvvmFX#348]
Hi guys,
I just saw that the last version of mvvmfx uploaded to http://mvnrepository.com/ is release 0.4.0 while the current version is 1.3.0. 
It would be nice if someone could upload the missing versions (or even release 1.3.0) to it.

**Comment by manuel-mauky** [comment]
Hi Bennet,
we have changed the maven artifactId from "mvvmFX" to "mvvmfx" in the past (#278).

Version 0.4.0 was the last version with the old artifactid. Starting with 1.0.0 we have used the one with all lowercase. 

You can find the current version (1.4.1) in the maven central: http://mvnrepository.com/artifact/de.saxsys/mvvmfx
