### ISSUE TITLE
create mvvmfx-easydi module

### ISSUE THREAD

**Issue by manuel-mauky** [sialcasa/mvvmFX#349]
At the moment we have modules for CDI and guice. In addition to this we could create a module for [EasyDI](https://github.com/lestard/EasyDI) too so that projects with this di framework can be easily created.

This should be relatively easy to be done as EasyDI needs far less boilerplate code in comparison to CDI and guice.

**Comment by manuel-mauky** [comment]
I've renamed the method `configureBindings` to `initEasyDi`. 
This has 3 reasons:
1. It better matches what this method is used for. To configure bindings is the main purpose, however it can also be used to get dependency instances that are needed in the app class. As you can't use constructor injection in the app class, this is the only possible alternative. 
2. the term "Binding" can be missleading in the context of JavaFX app.
3. The method for initialization of mvvmFX is named `initMvvmFX`. In the Guice module the method to configure modules is named `initGuiceModules`. So the new naming better matches existing livecycle methods.

**Comment by mainrs** [comment]
Can be closed.
