### ISSUE TITLE
JavaViewStep needs a codeBehind method too

### ISSUE THREAD

**Issue by mipastgt** [sialcasa/mvvmFX#350]
You currently can create custom controls as FXML views by using the "root" and "codeBehind" methods of the FxmlViewStep. But if you want to use the same scheme with pure Java views, this does not work because the JavaViewStep does not have the corresponding "codeBehind" method. It would be nice if such a method could be added.

Here is a code example which shows the problem:

```
public class AboutView extends HBox implements JavaView<AboutViewModel> {

    @InjectViewModel
    private AboutViewModel viewModel;

    @InjectResourceBundle
    private ResourceBundle resources;

    public AboutView() {
        String aboutText;
        try {
            FluentViewLoader.javaView(AboutView.class).codeBehind(this).load(); // Here is the problem
            aboutText = resources.getString("about.text");
        } catch (Exception e) {
            aboutText = "???";
        }

        Label description = new Label(aboutText);
        setSpacing(10);
        setPadding(new Insets(20));
        getChildren().add(description);
    }

}
```

**Comment by manuel-mauky** [comment]
Hi,
thanks for your request. In our projects we were almost only using fxml views in the past so our focus wasn't on the java-only feature. But of cause your request is valid and I will add this feature in the next release.

**Comment by manuel-mauky** [comment]
The implementation of this was surprisingly easy. You can try it with the version `1.5.0-SNAPSHOT` that is pushed to the maven central snapshot repo. Please give feedback if everything works fine for your use case.

**Comment by mipastgt** [comment]
Thank you very much for the quick response. I've tried it out and it works for me :-)
