### ISSUE TITLE
Errors in examples on Scopes Wiki-Page

### ISSUE THREAD

**Issue by mipastgt** [sialcasa/mvvmFX#352]
The examples on the Scopes Wiki-Page contain several error.
Class and constructor names don't fit together.
".addListener" missing in first example.

**Comment by manuel-mauky** [comment]
I will check this. The scopes feature is not release yet and changes in the API may not be updated in the wiki. I will have a look at this. I've updated the scopes page with a warning that the feature is still beta at the moment to reduce confusion.

**Comment by mipastgt** [comment]
The errors have nothing to do with the Scope API. Just the example classes are wrong.

**Comment by manuel-mauky** [comment]
Sorry, you are absolutely right. I think these were copy+paste errors. I've fixed the wiki page. 
Many thanks for your finding.
