### ISSUE TITLE
ModelWrapper should support updating default values

### ISSUE THREAD

**Issue by sideisra** [sialcasa/mvvmFX#366]
The ModelWrapper has the abbility to set default values for each wrapped value. When `reset` is called the constucted fields will get these default values.
The default can be set initially only but under some circumstances it is necessary to update these values to the current model values.

It would be great when ModelWrapper provides an `updateDefaults` method which loads the values from the model and sets them as new default values so that subsequent `reset` calls rest the values to the new ones.

**Comment by manuel-mauky** [comment]
Thanks for the pull request. Code was merged with #367 with a slightly renamed method name.
