### ISSUE TITLE
Reuse mvvmFX code

### ISSUE THREAD

**Issue by HS31** [sialcasa/mvvmFX#375]
I would really like to reuse the ModelWrapper from your library in one of my projects. Would it be ok if I just copy the need files into my project and give credit to it (linking to this github page) plus including the license file in my project?

**Comment by manuel-mauky** [comment]
Hi,
yes the way you describe it it's perfectly fine. 
The code is licensed under the Apache V2 license which supports such usage.

May I still ask what the reason is you don't like to use the classes directly from the library?

**Comment by HS31** [comment]
It just that I really only need those classes. I mean, I can still import it via maven and just use the classes. I just thought that why should I deliver classes that I do not use...

**Comment by HS31** [comment]
Ye nevermind, I will just import the whole library and simply use those classes. Less work 😄

**Comment by manuel-mauky** [comment]
Nice to hear :-)
