### ISSUE TITLE
Move DependencyInjector to public APi

### ISSUE THREAD

**Issue by sialcasa** [sialcasa/mvvmFX#388]
I'd like to use the DependencyInjector to create manually an instance for a type. Therefore it would be practical to use DependencyInjector.getInstance().getInstanceOf(..) but it is in the private API

**Comment by manuel-mauky** [comment]
I think you should use the DI container specific way of creating instances. 
With CDI this would look like this:

```
SomeClass someClass = CDI.current().select(SomeClass.class).get();
```

or

```
@Inject
private Instance<SomeClass> instance;

public void initialize() {
    SomeClass someClass = instance.get();
}
```

The advantage of this is that you can use the powerful API of CDI, for example to select instances with a given Annotation or instances of classes with specific generic type parameters.

In my oppinion we shouldn't introduce a less powerful API for something that is task of the DI framework.

**Comment by sialcasa** [comment]
Yes, my thought was to be more agnostic of the used DI Container but it's ok for me to no expose the private api.
