### ISSUE TITLE
[commands] Restart of DelegateCommand

### ISSUE THREAD

**Issue by tfleis** [sialcasa/mvvmFX#399]
A JavaFX Service can be restarted by calling `Service.restart()`. If there is a current running task it is cancelled. The behaviour of a DelegateCommand is different. When you execute the DelegateCommand twice it is only started once.

```
if (inBackground) {
  if (!super.isRunning()) {
    reset();
    start();
  }
} 
```

A DelegateCommand is a Service so we can call `DelegateCommand.restart()` directly. By doing that we don't gain the advantages of the Command class (e.g. testability).

My expectation is:

```
if (inBackground) {
  super.restart();
} 
```

**Comment by mainrs** [comment]
I understand your argumentation. I would expect the same behavior as you. Still, would like to here something from @lestard or @sialcasa concerning this.

**Comment by manuel-mauky** [comment]
Sorry, I hadn't had time to respond. I will look into this issue on monday.

**Comment by manuel-mauky** [comment]
I've created [a test case](https://github.com/sialcasa/mvvmFX/commit/b12149e597a69cd810be4350b732ee4d570cf536#diff-c2d0a1185e92b4179713f95601d254c4R264) that verifies that both service and delegate command have equal behaviour regarding restarting. It works with your suggested fix. 

As far as I can see this should work but I'm not as experienced as alex when it comes to Services and Commands. @sialcasa can you please review this issue and the provided fix?
