### ISSUE TITLE
[ModelWrapper] Copy of model with current values of properties

### ISSUE THREAD

**Issue by pkantner** [sialcasa/mvvmFX#421]
As extension it would be useful, if you can get a copy of the wrapped model with the current values of each property.

Example:

``` java
public void fill(M model) {
    if (model != null) {
        fields.forEach(field -> field.commit(model));
    }
}
```

So you can work with a copy of the model before committing it.

**Comment by manuel-mauky** [comment]
Hi Philipp,
thanks for your proposal. This looks useful for some use cases. 
I would name the method "copyValuesTo" instead of "fill" as it better describes what happens.

**Comment by manuel-mauky** [comment]
You can test the feature with version `1.6.0-SNAPSHOT`.

**Comment by pkantner** [comment]
Looks good :+1: Thank you
