### ISSUE TITLE
Potential Leak in ListenerManager

### ISSUE THREAD

**Issue by sialcasa** [sialcasa/mvvmFX#44]
The listener cleaner holds a reference on the listener and the property. This could be a possible memory leak, if the cleaner was not cleaned.

**Comment by manuel-mauky** [comment]
After some testing I couldn't find memory leaks when the ChangeListener was implemented with an anonymous inner class. 

But when I use lambda expressions to create the listener there is a leak. But thats not the only problem: In this case even the clean method of the ListenerManager doesn't work. There are still references to the listener after the clean up. 

I'm working on this....
