### ISSUE TITLE
check compatibility for jdk9 jigsaw

### ISSUE THREAD

**Issue by manuel-mauky** [sialcasa/mvvmFX#440]

**Comment by muxmax** [comment]
I'm doing some checks on the compatibility.

First the results of the dependency analysis using jdeps:

```
jdeps -R -jdkinternals Downloads/mvvmfx-1.6.0.jar 
jdeps -R -jdkinternals Downloads/mvvmfx-cdi-1.6.0.jar
jdeps -R -jdkinternals Downloads/mvvmfx-easydi-1.6.0.jar 
jdeps -R -jdkinternals Downloads/mvvmfx-guice-1.6.0.jar 
jdeps -R -jdkinternals Downloads/mvvmfx-testing-utils-1.6.0.jar 
jdeps -R -jdkinternals Downloads/mvvmfx-utils-1.6.0.jar 
```

All these calls of the tools resulted in empty output, which means there don't seem to be transitive or direct jdk-internal dependencies that had to be migrated.

Currently I'm working on a little Jigsaw project setup which also uses mvvmFX. I will post a link to the repository that contains this setup in a separate branch.

Using only the core of mvvmFX framework I just compiled and run a little JavaFX-App. The mvvmFX-JAR was included as is, and then put on the module path. That means the mvvmFX-JAR should be treated as an _Automatic Module_.

In the following days I would try a setup where the CDI-part is also included and used.

**Comment by manuel-mauky** [comment]
First tests imply that mvvmFX works with the next Java version 9. However, as the final version isn't released yet it's still possible to find problems when the final version is ready.
I will keep this issue open until we have checked actuall applications with the final version of Java 9.
