### ISSUE TITLE
Getting a Unit Test Failure on a Path with Spaces

### ISSUE THREAD

**Issue by bekwam** [sialcasa/mvvmFX#444]
I'm getting this error.  My project is installed and running the unit tests from a directory with spaces in it.

18:29:15.049 [JavaFX Application Thread] ERROR d.s.m.e.c.model.CountrySelector - A problem was detected while loading the XML file with the available countries.
java.io.FileNotFoundException: /media/carl/Extra%20Drive%201/git/mvvmFX.git/examples/contacts-example/target/test-classes/countries/iso_3166.xml (No such file or directory)

**Comment by manuel-mauky** [comment]
Hi. Thanks for your fix.
