### ISSUE TITLE
Show async behavior with CompletableFuture in examples/documentation

### ISSUE THREAD

**Issue by manuel-mauky** [sialcasa/mvvmFX#446]
We should provide an example of how to use `CompletableFuture` to implement async behavior.

**Comment by gtnarg** [comment]
If you are able to add an unpolished example here (prior to closing this issue) it would be appreciated as I have a need for this :)

**Comment by manuel-mauky** [comment]
Hi,
I've added a small app with a backend service that simulates delays and sometimes "connection error".
In the frontend I've used CompletableFuture to handle async usage of the backend service and error handling. 

Take a look at the example and tell me what you think.

**Comment by gtnarg** [comment]
This is great - thank you very much for the quick response!

I will review and let you know if I have any questions or feedback.
