### ISSUE TITLE
Adding external modules to Guice

### ISSUE THREAD

**Issue by jpitchardu** [sialcasa/mvvmFX#463]
I've a layered system, and each layer has a Module so I've:

- BusinessModule
- DataAccessModule
- UIModule

However there seems to be no way of adding them to the main injector. I've looked at the Welcome Example, but is far too simple.

Any insights are highly appreciated.

**Comment by manuel-mauky** [comment]
Hi,
in your main class that extends from `MvvmfxGuiceApplication` you can overwrite the method [initGuiceModules](https://sialcasa.github.io/mvvmFX/javadoc/1.5.0/mvvmfx-guice/de/saxsys/mvvmfx/guice/MvvmfxGuiceApplication.html#initGuiceModules-java.util.List-). This gets a list of guice modules as argument and you can add your modules to this list.

I have to admit that this isn't really explained in the documentation so I will add a few sentences about this topic in the wiki.

**Comment by jpitchardu** [comment]
Thanks

Yeah I went all the way to **fx-guice** and saw the examples.

If there is anything I can do to help you guys, just tell me.  I've really liked this framework.

**Comment by manuel-mauky** [comment]
Thanks for the offering. 
You can provide feedback on how the guice integration works for you.
In our projects in our company we are using the CDI version most of the time and therefor have little feedback for the guice version.
