### ISSUE TITLE
Generic Views

### ISSUE THREAD

**Issue by jpitchardu** [sialcasa/mvvmFX#464]
I'm sorry, this is my third issue in two weeks, I'm having trouble when implementing a Strategy Pattern with a generic view, this is the idea:

    public abstract class ManagerView< T extends ManagerViewModel >
        implements FxmlView< T>, Initializable {
        @InjectViewModel
        private T viewModel;
    }

    public class TicketManagerView< T extends TicketManagerViewModel >
        extends ManagerView< T > {}

So, we have several ViewModels with different configurations

    public abstract class ManagerViewModel {
        protected abstract void load();
    }

    public class TicketManagerViewModel extends ManagerViewModel {
        protected void load(){ service.getAll()}
    }

    public class TicketsByClientViewModel extends TicketManagerViewModel {
        @Override
        protected void load() { service.getByClient() }
    }

But when I have a 

    @FXML
    private TicketManagerView<TicketsByClientViewModel> ticketManagerController;

Somehow the Injected ViewModel is of Type `TicketManagerViewModel`.

Any ideas?

**Comment by manuel-mauky** [comment]
Hi,
no need to apologize for adding issues. Of course you are welcome to add ideas and feature requests.

In JavaFX it's not possible to define a generic class as Controller for an FXML file. In your FXML files you need to define `fx:controller=...` and you can't use a generic type in this place. This is a restriction of JavaFX in general and not mvvmFX. 

We can't load generic view classes out of the box. You have to create a class for each of your views. It doesn't even need to have any code. For example:

```java
public class TicketsByClientView extends TicketManagerView<TicketsByClientViewModel> {}
```
This one-line Class should be sufficient. Now you can use this class in your fxml file and it can be loaded by JavaFX.

Another hint: It doesn't matter what type you define when you inject the view-controller with '@FXML'  like in your last code example. This only injects an instance of the controller class but doesn't "control" which class is used as controller. The FXMLLoader (the JavaFX class that actually loads FXML files) only looks at the `fx:controller` attribute to decide which class to use. 


What's happening under the hood is the following: JavaFX FXMLLoader is parsing the fxml file and when it find's an attribute `fx:controller` it asumes that this is the controller class. Then it gives mvvmFX a .class-reference for this controller and mvvmFX returns an actual instance for this class-reference. This instance of the View-controller will have the viewModel injected and the only information we have to decide which viewModel class to use is the class reference. After mvvmFX has created the viewcontroller with the viewModel injected it passes this instance back to the FXMLLoader which then injects the controller instance into the parent controller instance when there is a field for injection (fieldname ends with "Controller" and `@FXML` annotation is present). At this point in time when the FXMLLoader reads if such field is present the actual View/ViewModel already exists and therefore it can't use this information to decide which class to use. 

I hope this helps you a bit to understand what's going on under the hood and I hope I was able to help you. If you have further questions don't hesitate to ask.

**Comment by jpitchardu** [comment]
Thank You @lestard, in fact, as you may see, I'm just starting with JavaFX, I come from a Swing / C# / Back-End Background, so ...

**Comment by manuel-mauky** [comment]
That's no problem. Developers from other framework/languages can bring in new ideas so I'm happy to hear about these ideas and use cases. Even if they aren't possible with our framework it's interesting to think about them.
