### ISSUE TITLE
Interface for Initiating the Model

### ISSUE THREAD

**Issue by stefanil** [sialcasa/mvvmFX#47]
Another task wich we often had to solve was to intantiate the model of a view tuple just after the tuple was created, especially in the case we had to instantiate it at runtime, f.e. to dynamically assemble composite views. See the following method, which for example could be called in response to a ui request done by the user.

<pre>
private void openWindow(String userId) {

        Stage stage = new Stage();
        final ViewTuple<MainContainerViewModel> tuple = viewLoader
                .loadViewTuple(MainContainerView.class);
        
        // lazy init / set model property or model instance
        tuple.getCodeBehind().getViewModel().setModel(someProperty());      

        // open a new stage
        final Parent control = tuple.getView();
        final Scene scene = new Scene(control);
        stage.setScene(scene);
        stage.show();
}
</pre>

This issue is about complementing the ViewModel interface with an optional method to override as the following (and so turn into an abstract class), just to make code written with the help of MvvmFX more readable.

<pre>
public void setModel(Object... model);
</pre>

Maybe we could also use generics, but this could be over engineered somehow.

**Comment by manuel-mauky** [comment]
The `ViewModel` is only an interface and no abstract class. Therefore it isn't possible to create an abstract method `setModel`. 

The MVVM design pattern doesn't describe how exactly the ViewModel accesses the Model. In my opinion our framework shouldn't dictate this either. It's the task of the Dependency Injection mechanism. To define a setter like in your example can be a simple and suitable solution but there are other possible solutions too and we shouldn't force the user to use one of them.

Therefore I'm closing this issue now.
