### ISSUE TITLE
Validation Status is `true` by default (Linked Validators)

### ISSUE THREAD

**Issue by jpitchardu** [sialcasa/mvvmFX#477]
I get that `ValidationStatus::isValid` returns based on the number of errors so the default return value is true. Nonetheless when trying to do something like:

``` java
curpValidator = new ObservableRuleBasedValidator();
electorKeyValidator = new ObservableRuleBasedValidator();

BooleanBinding curpValidationBinding = Bindings.createBooleanBinding(() -> {
    Predicate<String> validationPredicate = stringIsNotBlank
        .and(x -> x.matches(curpPattern))
        .or(x -> electorKeyValidator.getValidationStatus().isValid());

        return validationPredicate.test(electorKey.get());
    }, curp, electorKey);

BooleanBinding electorKeyValidationBinding = Bindings.createBooleanBinding(() -> {

    Predicate<String> validationPredicate = stringIsNotBlank
        .and(x -> x.matches(electorKeyPattern))
        .or(x -> curpValidator.getValidationStatus().isValid());

            return validationPredicate.test(electorKey.get());

    }, curp, electorKey);

    curpValidator.addRule(curpValidationBinding, ValidationMessage.error(""));
    electorKeyValidator.addRule(electorKeyValidationBinding, ValidationMessage.error(""));
``` 

It evaluates both like valid on the beginning, the idea is that the user must write one or both, so if one is valid the other one is not needed.

What do you think?

**Comment by manuel-mauky** [comment]
Hi, 
As far as I see your first validator depends on the second validator and vice versa.
I can imagine that this leads to unexpected behaviour but I haven't tested it yet.
In your code some variables are missing (`curpPattern`, `electorKey`, `curp`, `electorKeyPattern`). If you could provide these it would make testing easier. 

Regardles of this, maybe you can express your validation logic with a single BooleanBinding? 
Can you define a single pure function that takes  both `curp` and `electorKey` as arguments and returns `true` or `false` whether it is valid or not? I don't actually know your actual validation logic but most likely it should be possible to refactor it in such a way.

**Comment by jpitchardu** [comment]
@lestard Well the idea of the `BooleanBinding` worked well, so thanks
