### ISSUE TITLE
NullPointerException in DelegateCommand

### ISSUE THREAD

**Issue by AKreisel** [sialcasa/mvvmFX#478]
With issue #442 DelegateCommand was improved to provide information about exceptions that took place during execution. But this fix may produce a NullPointerException if the exeception occurs already in the ActionSupplier:
``` java
private void callActionAndSynthesizeServiceRun() {
  try {
    [...]
    // This line throws an exception
    Action action = actionSupplier.get();

    // This line initializes the "writeableExceptionProperty" but is never reached
    setWritableExceptionProperty(action);
    [...]
  } catch (Exception e) {
    // This line accesses the "writeableExceptionProperty", which is null at this point, and produces a NullPointerException
    setException(e);
    // This line won't be reached because of the above NullPointerException
    LOG.error("Exception in Command Execution", writableExceptionProperty.getValue());
    [...]
  }
}
```
Unfortunately the code logging the original exception will not be executed as well because of the NullPointerException.

**Comment by manuel-mauky** [comment]
Thanks a lot for this report. 
I've created a fix in #479. 
The fix will be part of the next maintenance release 1.6.1 and until then you can test it with version 1.6.1-SNAPSHOT.
