### ISSUE TITLE
Update Guice version.

### ISSUE THREAD

**Issue by manuel-mauky** [sialcasa/mvvmFX#490]
`mvvmfx-guice` uses `fx-guice:8.0.0` as dependency which itself uses `guice:3.0` but the latest release of Guice is version 4.1.

Update to new version 4.1. This can include a pullrequest to fx-guice project. However, in the long run it would be better to find an independend solution so that we can update our dependencies on our own.
Even better would be to provide a solution so that the user of mvvmfx-guice can choose her desired version.

**Comment by mka-codelake** [comment]
Hello,

do you have any plans for handling this issue in the near future? As far as I can see, the last update of fx-guice project was 3 years ago. So I assume that they won't bring out a new version.

Best Regards

Michael Kagel

**Comment by manuel-mauky** [comment]
Hi Michael,
at the moment this issue has a low priority because we don't have projects with guice in the company at the moment.
But if this issue is important for you I can put this on my list for the near future.

I think that we should remove the dependency to fx-guice altogether and completely reimplement the guice support. This would give us more flexibility in updating to newer versions of guice in the future.
However, it may break some application because fx-guice is providing some special features (like annotation `@FXMLController`) that won't work anymore, even though I don't know if someone ever had used any of these features.

If you like you can also provide a Pull-Request for this issue? I've implemented [support for Spring Boot](https://github.com/sialcasa/mvvmFX/pull/564) not long ago, which could be used as a guidance.

**Comment by mka-codelake** [comment]
Hi,

yes, we use guice in our project now. Currently we're searching for a good base framework for our JavaFx application and mvvmfx seems to be the best fit. The only point for now is, that we use guice 4.2, thus we are not sure about mvvmfx. 

Perhaps it is possible to build the new Guice module in a way that the main feature (using Guice) works and additional features (like annotations of fx-guice) can be reimplemented in future versions.

I will have a look if it is feasible for us to implement this module but this is not our decision ;-)
So I would be very thankful if this issue comes to your list.

Best Regards

Michael Kagel

**Comment by manuel-mauky** [comment]
I've re-implemented the guice module. You can try it out with the latest snapshot version.

When I tried the new module in our [example-app]() it worked out of the box with guice version 4.1.0 but when I updated to 4.2.2 I got an exception in the first run. After some googling I found out that an old version of google guava was the problem. After updating the guava version it worked as expected.

I've set the maven versioning so that you can use any guice version starting with 3.0. The mvvmfx-guice module now doesn't bring it's own guice version. You have to add a guice dependency with your desired version on your own.

**Comment by mka-codelake** [comment]
Thanks a lot for this really quick support! I just tested it with a local clone of your dev repository and it seems to work fine along with guice version 4.2.2.

Do you know when you will officially release this version on maven?

**Comment by manuel-mauky** [comment]
We don't have a strict release plan. Instead we do releases as soon as I think we have a good amount of improvements and features - or if someone needs a new feature as soon as possible. 

So I think I will do a new release in the near future. I hope I find the time within the next 1-2 weeks. There are still 2 PRs (#569 & #562) open that I need to review and include in the new release.

**Comment by manuel-mauky** [comment]
I'm sorry for the delay. I'm finished with the PRs that were targeted for the next release. I'm now doing the last preparations to release the new version.
