### ISSUE TITLE
Throw an exception if the fx:controller tag in a fxml file refers to a ViewModel instead of to a View.

### ISSUE THREAD

**Issue by tranquility79** [sialcasa/mvvmFX#498]
For some reason, I write fx:controller="de.foo.FancyViewModel" instead of "fx:controller="de.foo.FancyView". This error is hard to find because I get no error message. It just does not work. A special exception would be very helpful.

**Comment by manuel-mauky** [comment]
Thanks for the proposal.
For this we need to add a check in the `FluentViewLoader` after line [290](https://github.com/sialcasa/mvvmFX/blob/develop/mvvmfx/src/main/java/de/saxsys/mvvmfx/internal/viewloader/FxmlViewLoader.java#L286-L290) and the same check also after line [394](https://github.com/sialcasa/mvvmFX/blob/develop/mvvmfx/src/main/java/de/saxsys/mvvmfx/internal/viewloader/FxmlViewLoader.java#L394).

The check would look like this:
```java
if (controller instanceof ViewModel) {
    throw new IllegalStateException("A ViewModel class [" + controller.getClass() + "] was references in the FXML file. Instead the class that implements FxmlView has to be defined as fx:controller in the FXML.");
}
```
