### ISSUE TITLE
Scope is null in one of the 2 Viewmodels

### ISSUE THREAD

**Issue by f4bsn** [sialcasa/mvvmFX#507]
I'm trying to share the playlist (ObservableList<Song>) between the PlaylistViewModel and the ControlsViewModel.
I created a scope PlaylistControlsScope: 

```
public class PlaylistControlsScope implements Scope {

    private ObservableList<Song> playlist = FXCollections.observableArrayList();

    public ObservableList<Song> getPlaylist() {
        return playlist;
    }

    public void setPlaylist(ObservableList<Song> playlist) {
        this.playlist = playlist;
    }
}

```
In both ViewModels I have: 

`@InjectScope
    private PlaylistControlsScope scope;`

and in the MainContainerViewModel I have: 
`@ScopeProvider(scopes = {PlaylistControlsScope.class})`

the FXML structure is: 
```
<VBox id="mainContainer" xmlns:fx="http://javafx.com/fxml/1" xmlns="http://javafx.com/javafx/8.0.40"
      fx:controller="io.audiocracy.ui.maincontainer.MainContainerView" prefHeight="800.0" prefWidth="1280.0">
    <fx:include fx:id="MenuBar" source="../menubar/MenuBarView.fxml"/>

    <SplitPane id="table-container" dividerPositions="0.6" focusTraversable="true" VBox.vgrow="ALWAYS">
        <fx:include fx:id="Library" source="../library/LibraryView.fxml"/>
        <fx:include fx:id="Playlist" source="../playlist/PlaylistView.fxml"/>
    </SplitPane>

    <BorderPane id="bottom_container" prefHeight="200.0" prefWidth="200.0">
        <center>
            <fx:include fx:id="Controls" source="../bottombar/ControlsView.fxml"/>
        </center>

        <right>
            <fx:include fx:id="VolumeStatus" source="../bottombar/VolumeStatusView.fxml"/>
        </right>

        <left>
            <fx:include fx:id="NowPlaying" source="../bottombar/NowPlayingView.fxml"/>
        </left>

        <top>
            <fx:include fx:id="Progress" source="../bottombar/ProgressView.fxml"/>
        </top>
    </BorderPane>
</VBox>
```

In PlaylistViewModel I'm updating the instance of playlist in PlaylistControlsScope whenever it changes. When I'm trying to get the playlist inside of ControlsViewModel with scope.getPlaylist() my scope is null. Any ideas why the scope is not injected in this ViewModel?

**Comment by manuel-mauky** [comment]
A common problem is to access the scope instance in the constructor of the ViewModel. This isn't possible because the scope is injected after the controller is executed. Instead you need to create a method `public void initialize()` that will  be invoked by the framework after injection is done.

**Comment by f4bsn** [comment]
Ah thanks so much! That got me on the right track! It was definitely my mistake. ;)
