### ISSUE TITLE
MVVM bidirectional binding with table

### ISSUE THREAD

**Issue by baldeep011** [sialcasa/mvvmFX#509]
Hi All,
I am implementing MVVM framwork using javafx, I am trying to bind table columns wtih view model. but it is displaying no values in the table.

Can any one suggest me any simple example in which data binding with table columns .

Thanks, waiting for response.

**Comment by manuel-mauky** [comment]
Hi,
our [contacts example](https://github.com/sialcasa/mvvmFX/tree/develop/examples/contacts-example) is using the TableView to show contacts data. The interesting files are [here](https://github.com/sialcasa/mvvmFX/tree/develop/examples/contacts-example/src/main/java/de/saxsys/mvvmfx/examples/contacts/ui/master).

I hope this gives you a clue on how to use the TableView with mvvmFX.
