### ISSUE TITLE
Can`t use WebView (and WebEngine) in the View class. Cant initialize scene. 

### ISSUE THREAD

**Issue by w0rxbend** [sialcasa/mvvmFX#515]

**Comment by w0rxbend** [comment]
It does not work only if use loading mvvmFX scenes in a background thread

**Comment by w0rxbend** [comment]
I tried to implement async loading of view-tuple. But it impossible with your example. Always i get setOnFailed handler in Task. Also i tried to do this with ComplatableFuture, also impossible.

**Comment by manuel-mauky** [comment]
You've closed this issue so I assume that your problem is fixed?

**Comment by w0rxbend** [comment]
@lestard, Yes, i fixed my problem.
