### ISSUE TITLE
TextField with search options only starts with

### ISSUE THREAD

**Issue by baldeep011** [sialcasa/mvvmFX#528]
Hi,
I have to create a search textfield (autocompletion) but for starts with only. I know there is  TextFields.bindAutoCompletion API also but is shows only contains not starts with. 

Is there any existing example in FX or I have to create one. 

Regards
Baldeep Singh

**Comment by manuel-mauky** [comment]
Hi, 
sorry, I've totally missed your issue. 
I don't know a util or API for your use case.

Regards
Manuel
