### ISSUE TITLE
DelegateCommand cannot be extended

### ISSUE THREAD

**Issue by ntherrien** [sialcasa/mvvmFX#536]
The following fields are set as private:

    private final Supplier<Action> actionSupplier;
    private boolean inBackground;

Can we se all fields to a minimum of Protected so that we can extend the DelegateCommand class?

**Comment by manuel-mauky** [comment]
Thanks for the suggestion. 
Yes, I think this would be possible. At least I don't see any reason that would prevent us from doing this.

If you like, you can provide a PullRequest for this and I will merge it as fast as possible.

**Comment by ntherrien** [comment]
Hi!
PullRequest has been submitted.

I have committed some changes on the project's develop branch by mistake. I have reverted that and moved my change to my fork and a separate branch.

Regards,

**Comment by manuel-mauky** [comment]
PR is merged. Thanks for the contribution
