### ISSUE TITLE
Incorrect exception message in ViewLoaderReflectionUtils

### ISSUE THREAD

**Issue by nils-christian** [sialcasa/mvvmFX#543]
Hi,

I think I found a minor bug (it is more an incorrect description in an exception message). Trying to use a scope without scope provider leads to the following message:

`A scope was requested but no @ScopeProvider found in the hirarchy. Declare it like this: @ScopeProvider(kieker.diagnosis.ui.scopes.ProgressDialogScope)`

Correct _hirarchy_ to _hierarchy_
and it should rather be
`Declare it like this: @ScopeProvider ( scopes = ProgressDialogScope.class )`
or
`Declare it like this: @ScopeProvider ( scopes = kieker.diagnosis.ui.scopes.ProgressDialogScope.class )`

As an alternative, you could also add _values_ as a name alias for _scopes_, which would allow to do this:
`@ScopeProvider ( ProgressDialogScope.class )`

The exception is thrown in _ViewLoaderReflectionUtils.injectScopeIntoField_.

**Comment by manuel-mauky** [comment]
Thanks for the hint. You are right, this has to be fixed.
I also like the idea of "values" as alias in the annotation.

If you like you could provide a Pull-Request for this?

**Comment by nils-christian** [comment]
Hi,

Yes, of course. I opened a pull request. Details are provided in said request.

**Comment by nils-christian** [comment]
Hi,

I think we can close this ticket, right?

Best regards,

  Nils
