### ISSUE TITLE
ClassNotFoundException for PostConstruct with Java 9

### ISSUE THREAD

**Issue by nils-christian** [sialcasa/mvvmFX#547]
Hi,

With the transition Java 8 -> Java 9, the rt.jar was (I think) removed and the classes were moved to other modules. This means also, that some of the classes are now part of the Java EE API and no longer part of the Java SE API. This includes the class "PostConstruct", which is by default no longer available in a JRE 9. As you check for this annotation in _ViewLoaderReflectionUtils.initializeViewModel(ViewModelType)_, one gets a class not found exception:
`Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct`

Possible workarounds:
* Add a maven dependency containing this class
```
<dependency>
    <groupId>javax.annotation</groupId>
    <artifactId>javax.annotation-api</artifactId>
    <version>1.3.2</version>
</dependency>
```
* Add the necessary module
`--add-modules java.xml.ws.annotation`

I am not sure what would be a good solution for the mvvmFX code. Maybe catching the exception at least? Using reflection to identify the annotation by name?

This issue is related to #440.

**Comment by manuel-mauky** [comment]
Thanks for this hint. There was a similar question on stackoverflow some time ago but I wasn't sure what the best solution for this issue would be. 
I think there are 3 possible solutions (in this order):

1) check by name
2) catch the exception and rethrow it with a meaningful description of how to fix the issue.
3) add javax.annotation-api to dependencies of mvvmFX

**Comment by nils-christian** [comment]
Hi,

Maybe:
* Try and load "javax.annotation.PostConstruct" with _Class.forName_ (once, because this method is slow). If it cannot be found, it cannot be available in the classpath and thus a method can not be annotated with it.
* If it is in the classpath, you can still use _isAnnotationPresent_ to check for it.

However, mvvmFX is not really using the _PostConstruct_ method. It just checks for it. One could also argue that it is not the task of mvvmFX to check for such invalid constructs, especially because there is more than one CDI framework out there which could initialize the view model a second time. And if _PostConstruct_ is no longer part of the SE library with Java 9, maybe mvvmFX shouldn't even try and check this.

Best regards,

  Nils

**Comment by manuel-mauky** [comment]
Strictly speaking it's not the task of mvvmFX to check for this. On the other hand, for users of the framework this error is easy to make and hard to find. And it is not unusual to make this misconfiguration. Our goal is to make development as easy as possible and to point users to problems as good as possible. So I think we should keep this check.

I have an alternative solution:

```java
boolean postConstructAnnotationPresent = Arrays.stream(initMethod.getAnnotations())
					.map(Annotation::annotationType)
					.map(Class::getName)
					.anyMatch(annotationType -> annotationType.equals("javax.annotation.PostConstruct"));

if(postConstructAnnotationPresent) {
	throw new IllegalStateException(...);
}
```

What do you think?

**Comment by nils-christian** [comment]
Hi,

I see. Well, from the looks of it, your solution should work. One could think about a solution that wouldn't require iterating over all annotations from the method, but then again the initialize method is not the most often called method and shouldn't have that much annotations anyway. I would prefer this solution.

Best regards

  Nils
