### ISSUE TITLE
Extend naming convention so that "MainView" is possible for a main.fxml file

### ISSUE THREAD

**Issue by manuel-mauky** [sialcasa/mvvmFX#55]
At the moment the naming conventions say that the filename of an fxml file has to be the same (case insensitive) as the View class name.
When my View class is named "MainView" the fxml file has to be named "mainView.fxml" (or "mainview.fxml"...). 

In my opinion at the level of FXML files the string "View" in the filename is redundant. I would name the file only "main.fxml". 

On the other hand, at the level of java classes it makes sense to name the "code-behind" class "MainView.java". This way it`s easier to tell which part of the mvvm pattern the class is related to. 
But at the moment this naming combination isn't possible with mvvmfx.

The question is: Should be extend the naming convention so that the user can name the fxml file "main.fxml" and the code-behind "MainView.java"? Or should we stay at the current naming convention?

**Comment by sialcasa** [comment]
different cases are possible, different names nottttttt

**Comment by manuel-mauky** [comment]
I was wrong in the issue description. At the moment we are case sensitive so when the view class is named "MainView" the fxml file has to be named "MainView.fxml". "mainView.fxml" or "mainview.fxml" does NOT work in generall but only on Windows. On linux and MacOS you would get an exception because these OSs support case sensitive file names.

After thinking a little bit about this issue I think that we should stay with the current naming convention and make it clear that it is case sensitive. We should encourage developers to name there files case sensitive to prevent issues on Linux or MacOS.

For this reason I'm closing this issue without changes to the code.
