### ISSUE TITLE
Add Support for Spring-Boot

### ISSUE THREAD

**Issue by manuel-mauky** [sialcasa/mvvmFX#561]

**Comment by yunus89** [comment]
If support for spring boot is added, i will definately change our javafx app to use mvvmfx.

**Comment by manuel-mauky** [comment]
Nice to hear :-)
At the moment we are starting a new Application with Spring Boot and mvvmFX and so far it looks good. After some internal testing we will then push the spring-boot support to the framework. I hope that we can get it within the next month.

**Comment by manuel-mauky** [comment]
I've implemented basic support for Spring-Boot.
