### ISSUE TITLE
build upon fx-cdi for mvvmfx-cdi module

### ISSUE THREAD

**Issue by manuel-mauky** [sialcasa/mvvmFX#60]
Maybe our mvvmfx-cdi module can be build upon the new [cathive/fx-cdi](https://github.com/cathive/fx-cdi) project. This could lead to an API that is more similar to our guice module as it is also based on the fx-guice project from the same author. 

At the first glance fx-cdi looks great and we should evaluate it. 

The problem with our current cdi based Application class is that it doesn't subclass JavaFX's Application class. Maybe this is uncomfortable for some users and there are features missing for this reason. The fx-cdi Application class looks better when it comes to this issue.

**Comment by sialcasa** [comment]
I would continue using our implementation to be independent to other frameworks
