### ISSUE TITLE
Default value for the ModelWrapper field method

### ISSUE THREAD

**Issue by svedie** [sialcasa/mvvmFX#601]
When I define a `ModelWrapper` in the `ViewModel`:

`ModelWrapper<MyObject> wrapper = new ModelWrapper<>();`

all values of `MyObject` are initialized with `null`.

Now, when I use the `wrapper` to retreive the values and they are null, an `NullPointerException` is thrown.

This definition of an observable list property:
```
ObservableList<String> numberProperty() {
   return wrapper.field("number", MyObject::getNummer, MyObject::setNummer);
}
```
throws an `NullPointerException` if I use it to initialize an `ComboBox` or an `ListView`.

It would be helpfull, if one could define an default value in the `ModelWrapper` for the getter method. If there is no default value is defined, then the behavior is as now implemented.

**Comment by manuel-mauky** [comment]
Hi,
this is already possible. There are overloaded `field` methods that are taking an additional argument for the default value. See this example:

```java
public StringProperty nameProperty() {
	return wrapper.field("name", MyObject::getName, MyObject:setName, "default value here");
}
```

For your example with an observable list it would be:

```java
ObservableList<String> numberProperty() {
   return wrapper.field("number", MyObject::getNummer, MyObject::setNummer, new ArrayList<>());
}
```

**Comment by svedie** [comment]
Thanks!

I missed this one method :(
