### ISSUE TITLE
dagger as DI

### ISSUE THREAD

**Issue by brijesh-padsala** [sialcasa/mvvmFX#628]
I want to inject some class in Viewmodel using Dagger2 DI framework. How can i set custom DI for dagger-2 ?? any help ?

**Comment by manuel-mauky** [comment]
Hi,
MvvmFX needs to get instances of a class at runtime.
See https://github.com/sialcasa/mvvmFX/wiki/Dependency-Injection#other-dependency-injection-frameworks for a short description. You need to call [MvvmFX.setCustomDependencyInjector](https://sialcasa.github.io/mvvmFX/javadoc/1.3.0/mvvmfx/de/saxsys/mvvmfx/MvvmFX.html#setCustomDependencyInjector-javafx.util.Callback-) and pass it a callback function. That function takes a Class as argument and has to return an instance of that class.

I'm not sure about this but if I remember correctly, Dagger is doing compile-time DI while mvvmFX needs runtime-DI. If dagger provides a way to dynamically get instances of a specific class, you should be able to get it to work with the custom injection as described above.

**Comment by brijesh-padsala** [comment]
Hey,

Thanks for answering. As Dagger is compile time DI. I didn't found way to set Custom DI for dagger. But I found other way around to Inject DI in Viewmodels. 

Thanks for your time.
