### ISSUE TITLE
Access ViewModel 

### ISSUE THREAD

**Issue by sialcasa** [sialcasa/mvvmFX#78]
Durch den Wechsel von einem getter auf Annotationen in der view, um das ViewModel zu referenzieren, hat man nach dem laden einer view über den ViewLoader bzw. ViewTuple, keine Möglichkeit, das ViewModel zu referenzieren. Workaround ist, einen getter auf das ViewModel in der View zu erstellen.

Soll: ViewTuple hat einen getter auf das erstelle ViewModel.

**Comment by manuel-mauky** [comment]
In der aktuellen Implementierung des DI-mechanismus kann es passieren, dass das ViewModel für FxmlViews doppelt injekted wird:

Wenn der User sich aus der DI-Facade eine Controller-Instanz holt hat diese bereits ein ViewModel injekted.
Wird diese Instanz beim Aufruf von ViewLoader mitgegeben, dann wird im FxmlViewLoader trotzdem nochmal das ViewModel injekted und dabei das erste ViewModel überschrieben.
Dieses Verhalten sollte hier gleich mit gefixt werden da es direkt damit zusammenhängt.
