### ISSUE TITLE
CDI/Guice: Make the HostServices injectable.

### ISSUE THREAD

**Issue by manuel-mauky** [sialcasa/mvvmFX#99]
In a plain JavaFX application you can get the `HostServices` instances in the `Application` class. A typical usecase for HostServices is to open a website in the system web browser.

For CDI and Guice based applications it would be cool to be able to inject the HostServices instance.

**Comment by sialcasa** [comment]
I would not make the hostservices accessable, but the Application it self. An @Inject of the Application would be better or? @lestard

**Comment by manuel-mauky** [comment]
Are there any problems with using HostServices outside of the Application class that I have missed?

In respect to the "law of demeter" in my oppinion it's better to directly use the HostServices instead of injecting Application and then use "getHostServices" because I don't care where the HostServices comes from. I don't need the Application but only the HostServices for this usecase.

Besides this, making the Application injectable of cause would be possible too when it is needed for other use cases.

**Comment by sialcasa** [comment]
Agree
